server:
  port: 8085
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade
dubbo:
  application:
    name: trade-service-dubbo
    qos-enable: false
#    qos-port: 33333
#    qos-accept-foreign-ip: false
  registry:
    address: nacos://47.121.141.189:8848
  protocol:
    name: dubbo
    port: -1
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123