server:
  port: 8081
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
hm:
  swagger:
    title: 商品服务接口文档
    package: com.hmall.item.controller
  db:
    database: hm-item
dubbo:
  application:
    name: item-service-dubbo
  registry:
    address: nacos://47.121.141.189:8848
  protocol:
    name: dubbo
    port: -1
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123